server:
  port: 8080
  address: localhost

spring:
  application:
    name: sexhub-server
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sexhub
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 1
